[package]
name = "proof-of-sql-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = { version = "0.4.0", default-features = false }
ark-ec = { version = "0.4.0", default-features = false }
ark-serialize = { version = "0.4.0", default-features = false }
bincode = "1"
proof-of-sql = { version = "0.25.3", default-features = false }
proof-of-sql-parser = { version = "0.25.3", default-features = false }

[dev-dependencies]
proof-of-sql = { version = "0.25.3", default-features = false, features = ["test"] }
rstest = { version = "0.22.0" }
