[package]
name = "proof-of-sql-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-serialize = { version = "0.4.0", default-features = false }
bincode = "1"
blitzar = { version = "3.1.0", default-features = false, optional = true }
curve25519-dalek = { version = "4", optional = true }
proof-of-sql = { version = "0.15.0", default-features = false }
proof-of-sql-parser = { version = "0.15.0" }

[dev-dependencies]
proof-of-sql = { version = "0.15.0", default-features = false, features = ["test"] }

[features]
inner-product = ["dep:blitzar", "dep:curve25519-dalek", "proof-of-sql/blitzar"]
