[package]
name = "proof-of-sql-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = { version = "0.8.11", default-features = false }
ark-bls12-381 = { version = "0.4.0", default-features = false }
ark-ec = { version = "0.4.0", default-features = false }
ark-serialize = { version = "0.4.0", default-features = false }
bincode = "1"
indexmap = { version = "2.1", default-features = false, features = ["serde"] }
proof-of-sql = { version = "0.25.3", default-features = false }
proof-of-sql-parser = { version = "0.25.3", default-features = false }
serde = { version = "1.0" }

[dev-dependencies]
proof-of-sql = { version = "0.25.3", default-features = false, features = ["test"] }
rstest = { version = "0.22.0" }
