[config]
default_to_workspace = false

[tasks.ignore-members]
workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
dependencies = ["clean"]
command = "cargo"
args = ["build"]

[tasks.test]
dependencies = ["clean"]
command = "cargo"
args = ["test"]

[tasks.format_inst]
[tasks.format-inst]
install_crate = { crate_name = "rustfmt", rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "--help" }

[tasks.format]
dependencies = ["format-inst"]
command = "cargo"
args = ["fmt"]

[tasks.format-check]
dependencies = ["format-inst"]
command = "cargo"
args = ["fmt", "--check"]

[tasks.clippy-inst]
install_crate = { crate_name = "clippy", rustup_component_name = "clippy", binary = "clippy", test_arg = "--help" }

[tasks.clippy]
dependencies = ["clippy-inst"]
command = "cargo"
args = ["clippy", "--", "--deny", "warnings"]

[tasks.header-add]
script = [
    "if [ \"$#\" -lt 2 ]; then",
    "  echo 'Usage: $0 <header-file> <file-pattern>'",
    "  exit 1",
    "fi",
    "HEADER_FILE=\"$1\"",
    "FILE_PATTERN=\"$2\"",
    "LICENSE_HEADER=$(cat \"$HEADER_FILE\")",
    "shopt -s globstar",
    "for file in $FILE_PATTERN; do",
    "  if [[ -f \"$file\" && \"$file\" == *.rs ]]; then",
    "    if ! grep -q 'Copyright 2024, Horizen Labs, Inc.' \"$file\"; then",
    "      echo 'Adding license header to $file'",
    "      echo -e \"$LICENSE_HEADER\\n$(cat $file)\" > \"$file\"",
    "    fi",
    "  fi",
    "done"
]
args = ["HEADER-APACHE2", "./!(target)/**/*.rs"]

[tasks.header-check]
env = { CHECK_DIRTY = "true", DRY_RUN = "true" }
run_task = "header-add"

[tasks.audit-inst]
command = "cargo"
args = ["install", "cargo-audit"]

[tasks.audit]
dependencies = ["audit-inst"]
command = "cargo"
args = ["audit"]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "--workspace", "--lcov", "--output-path", "lcov.info"]

[tasks.udeps-inst]
command = "cargo"
args = ["install", "cargo-udeps", "--locked"]

[tasks.udeps]
dependencies = ["udeps-inst"]
command = "cargo"
args = ["udeps", "--all-targets"]



[tasks.ci]
dependencies = ["build", "test", "format", "header-add", "clippy", "audit"]

[tasks.ci-remote]
dependencies = ["build", "test", "format-check", "header-check", "clippy", "audit"]